using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Acidmanic.Utilities.Reflection.Attributes;
using Acidmanic.Utilities.Reflection.Extensions;

namespace Acidmanic.Utilities.Reflection.ObjectTree
{
    /// <summary>
    /// Methods of this class are useful to retrieve meta information given to properties of a class/model
    /// </summary>
    public static class FieldInfo
    {
        /// <summary>
        /// Checks for presence of <code>UniqueMember</code> attribute
        /// </summary>
        /// <param name="property">The field property to be checked</param>
        /// <returns>True if attribute has been found</returns>
        public static bool IsUnique(PropertyInfo property)
        {
            return Is<UniqueMemberAttribute>(property);
        }

        /// <summary>
        /// Checks for presence of <code>UniqueMember</code> attribute
        /// </summary>
        /// <param name="property">The field property to be checked</param>
        /// <returns>True if attribute has been found</returns>
        public static bool IsAutogenerated(PropertyInfo property)
        {
            return Is<AutoValuedMemberAttribute>(property);
        }

        
        private static bool Is<TAttribute>(PropertyInfo? property)
            where TAttribute : Attribute
        {
            if (property == null)
            {
                return false;
            }

            var attributes = property.GetCustomAttributeParametersIncluded<TAttribute>();

            return attributes.Count > 0;
        }
        
        /// <summary>
        /// Gets Proper name by searching field name Attributes 
        /// </summary>
        /// <param name="property">A PropertyInfo Object pointing to the field</param>
        /// <returns>Proper name for given field</returns>
        public static string GetMappedName(PropertyInfo property)
        {
            string name = property.Name;
            //TODO: Put naming conventions here   

            List<MemberNameAttribute> attributes = new List<MemberNameAttribute>();

            attributes.AddRange(property.GetCustomAttributeParametersIncluded<MemberNameAttribute>());

            if (attributes.Count > 0)
            {
                name = attributes.Last().Name;
            }

            return name;
        }
    }
}