using System;
using System.Collections.Generic;
using System.Linq;
using Acidmanic.Utilities.Reflection.ObjectTree;

namespace Acidmanic.Utilities.Reflection.Extensions
{
    public static class TypeExtensions
    {
        public static AccessNode GetUniqueIdFieldLeaf(this Type type)
        {
            var node = ObjectStructure.CreateStructure(type, false);

            var leaves = node.GetDirectLeaves();

            var idLeaf = leaves.FirstOrDefault(l => l.IsUnique);

            return idLeaf;
        }

        public static string GetIdFieldName(this Type type)
        {
            var idLeaf = type.GetUniqueIdFieldLeaf();

            return idLeaf?.Name;
        }


        public static List<AccessNode> ListAutoGeneratedFields(this Type type)
        {
            var list = new List<AccessNode>();

            var node = ObjectStructure.CreateStructure(type, false);

            var leaves = node.GetDirectLeaves();

            var autoGeneratedLeaves = leaves.Where(l => l.IsAutoValued);

            list.AddRange(autoGeneratedLeaves);

            return list;
        }
    }
}